db:
  restart: always
  container_name: db
  image: postgres
  volumes_from:
    - data
  ports:
    - "5432:5432"
data:
  restart: always
  container_name: data
  image: postgres
  volumes:
    - /var/lib/postgresql
  command: "true"
web:
  container_name: web
  build: ./web
  command: /usr/local/bin/gunicorn imageServerProj.wsgi:application -w 2 -b :8000
  volumes:
    - .:/usr/src/app/
  ports:
    - "8000:8000"
  links:
    - db
  environment:
    - DB_NAME=postgres
    - DB_USER=postgres
    - DB_SERVICE=db
    - DB_PORT=5432
    - PYTHONUNBUFFERED=0
nginx:
  restart: always
  container_name: nginx
  build: ./nginx/
  ports:
    - "80:80"
  volumes:
    - /www/static
  volumes_from:
    - web
  links:
    - web:web
