# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-09 06:42
from __future__ import unicode_literals

from django.db import migrations, models
import imageUploader.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='IMGFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imgFile', models.ImageField(upload_to=imageUploader.models.generate_filename)),
            ],
        ),
    ]
