# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-03 15:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imageUploader', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='imgfile',
            name='csv_index',
            field=models.IntegerField(default=0),
        ),
    ]
